import { CountryPrefix } from '../types';

// Simplified GS1 prefix list
const gs1Prefixes: CountryPrefix[] = [
  { prefix: '000-019', name: 'USA & Canada', code: 'US', flag: '🇺🇸' },
  { prefix: '020-029', name: 'Restricted Distribution', code: 'XX', flag: '🌐' },
  { prefix: '030-039', name: 'USA Drugs', code: 'US', flag: '🇺🇸' },
  { prefix: '040-049', name: 'Restricted Distribution', code: 'XX', flag: '🌐' },
  { prefix: '050-059', name: 'Coupons', code: 'XX', flag: '🎟️' },
  { prefix: '060-139', name: 'USA & Canada', code: 'US', flag: '🇺🇸' },
  { prefix: '200-299', name: 'Restricted Distribution', code: 'XX', flag: '🌐' },
  { prefix: '300-379', name: 'France', code: 'FR', flag: '🇫🇷' },
  { prefix: '380', name: 'Bulgaria', code: 'BG', flag: '🇧🇬' },
  { prefix: '383', name: 'Slovenia', code: 'SI', flag: '🇸🇮' },
  { prefix: '385', name: 'Croatia', code: 'HR', flag: '🇭🇷' },
  { prefix: '387', name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦' },
  { prefix: '400-440', name: 'Germany', code: 'DE', flag: '🇩🇪' },
  { prefix: '450-459', name: 'Japan', code: 'JP', flag: '🇯🇵' },
  { prefix: '460-469', name: 'Russia', code: 'RU', flag: '🇷🇺' },
  { prefix: '470', name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬' },
  { prefix: '471', name: 'Taiwan', code: 'TW', flag: '🇹🇼' },
  { prefix: '474', name: 'Estonia', code: 'EE', flag: '🇪🇪' },
  { prefix: '475', name: 'Latvia', code: 'LV', flag: '🇱🇻' },
  { prefix: '476', name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿' },
  { prefix: '477', name: 'Lithuania', code: 'LT', flag: '🇱🇹' },
  { prefix: '478', name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿' },
  { prefix: '479', name: 'Sri Lanka', code: 'LK', flag: '🇱🇰' },
  { prefix: '480', name: 'Philippines', code: 'PH', flag: '🇵🇭' },
  { prefix: '481', name: 'Belarus', code: 'BY', flag: '🇧🇾' },
  { prefix: '482', name: 'Ukraine', code: 'UA', flag: '🇺🇦' },
  { prefix: '484', name: 'Moldova', code: 'MD', flag: '🇲🇩' },
  { prefix: '485', name: 'Armenia', code: 'AM', flag: '🇦🇲' },
  { prefix: '486', name: 'Georgia', code: 'GE', flag: '🇬🇪' },
  { prefix: '487', name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿' },
  { prefix: '488', name: 'Tajikistan', code: 'TJ', flag: '🇹🇯' },
  { prefix: '489', name: 'Hong Kong', code: 'HK', flag: '🇭🇰' },
  { prefix: '490-499', name: 'Japan', code: 'JP', flag: '🇯🇵' },
  { prefix: '500-509', name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { prefix: '520-521', name: 'Greece', code: 'GR', flag: '🇬🇷' },
  { prefix: '528', name: 'Lebanon', code: 'LB', flag: '🇱🇧' },
  { prefix: '529', name: 'Cyprus', code: 'CY', flag: '🇨🇾' },
  { prefix: '530', name: 'Albania', code: 'AL', flag: '🇦🇱' },
  { prefix: '531', name: 'North Macedonia', code: 'MK', flag: '🇲🇰' },
  { prefix: '535', name: 'Malta', code: 'MT', flag: '🇲🇹' },
  { prefix: '539', name: 'Ireland', code: 'IE', flag: '🇮🇪' },
  { prefix: '540-549', name: 'Belgium & Luxembourg', code: 'BE', flag: '🇧🇪' },
  { prefix: '560', name: 'Portugal', code: 'PT', flag: '🇵🇹' },
  { prefix: '569', name: 'Iceland', code: 'IS', flag: '🇮🇸' },
  { prefix: '570-579', name: 'Denmark', code: 'DK', flag: '🇩🇰' },
  { prefix: '590', name: 'Poland', code: 'PL', flag: '🇵🇱' },
  { prefix: '594', name: 'Romania', code: 'RO', flag: '🇷🇴' },
  { prefix: '599', name: 'Hungary', code: 'HU', flag: '🇭🇺' },
  { prefix: '600-601', name: 'South Africa', code: 'ZA', flag: '🇿🇦' },
  { prefix: '603', name: 'Ghana', code: 'GH', flag: '🇬🇭' },
  { prefix: '608', name: 'Bahrain', code: 'BH', flag: '🇧🇭' },
  { prefix: '609', name: 'Mauritius', code: 'MU', flag: '🇲🇺' },
  { prefix: '611', name: 'Morocco', code: 'MA', flag: '🇲🇦' },
  { prefix: '613', name: 'Algeria', code: 'DZ', flag: '🇩🇿' },
  { prefix: '615', name: 'Nigeria', code: 'NG', flag: '🇳🇬' },
  { prefix: '616', name: 'Kenya', code: 'KE', flag: '🇰🇪' },
  { prefix: '618', name: 'Ivory Coast', code: 'CI', flag: '🇨🇮' },
  { prefix: '619', name: 'Tunisia', code: 'TN', flag: '🇹🇳' },
  { prefix: '621', name: 'Syria', code: 'SY', flag: '🇸🇾' },
  { prefix: '622', name: 'Egypt', code: 'EG', flag: '🇪🇬' },
  { prefix: '624', name: 'Libya', code: 'LY', flag: '🇱🇾' },
  { prefix: '625', name: 'Jordan', code: 'JO', flag: '🇯🇴' },
  { prefix: '626', name: 'Iran', code: 'IR', flag: '🇮🇷' },
  { prefix: '627', name: 'Kuwait', code: 'KW', flag: '🇰🇼' },
  { prefix: '628', name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦' },
  { prefix: '629', name: 'UAE', code: 'AE', flag: '🇦🇪' },
  { prefix: '640-649', name: 'Finland', code: 'FI', flag: '🇫🇮' },
  { prefix: '690-699', name: 'China', code: 'CN', flag: '🇨🇳' },
  { prefix: '700-709', name: 'Norway', code: 'NO', flag: '🇳🇴' },
  { prefix: '729', name: 'Israel', code: 'IL', flag: '🇮🇱' },
  { prefix: '730-739', name: 'Sweden', code: 'SE', flag: '🇸🇪' },
  { prefix: '740', name: 'Guatemala', code: 'GT', flag: '🇬🇹' },
  { prefix: '741', name: 'El Salvador', code: 'SV', flag: '🇸🇻' },
  { prefix: '742', name: 'Honduras', code: 'HN', flag: '🇭🇳' },
  { prefix: '743', name: 'Nicaragua', code: 'NI', flag: '🇳🇮' },
  { prefix: '744', name: 'Costa Rica', code: 'CR', flag: '🇨🇷' },
  { prefix: '745', name: 'Panama', code: 'PA', flag: '🇵🇦' },
  { prefix: '746', name: 'Dominican Republic', code: 'DO', flag: '🇩🇴' },
  { prefix: '750', name: 'Mexico', code: 'MX', flag: '🇲🇽' },
  { prefix: '754-755', name: 'Canada', code: 'CA', flag: '🇨🇦' },
  { prefix: '759', name: 'Venezuela', code: 'VE', flag: '🇻🇪' },
  { prefix: '760-769', name: 'Switzerland', code: 'CH', flag: '🇨🇭' },
  { prefix: '770-771', name: 'Colombia', code: 'CO', flag: '🇨🇴' },
  { prefix: '773', name: 'Uruguay', code: 'UY', flag: '🇺🇾' },
  { prefix: '775', name: 'Peru', code: 'PE', flag: '🇵🇪' },
  { prefix: '777', name: 'Bolivia', code: 'BO', flag: '🇧🇴' },
  { prefix: '779', name: 'Argentina', code: 'AR', flag: '🇦🇷' },
  { prefix: '780', name: 'Chile', code: 'CL', flag: '🇨🇱' },
  { prefix: '784', name: 'Paraguay', code: 'PY', flag: '🇵🇾' },
  { prefix: '786', name: 'Ecuador', code: 'EC', flag: '🇪🇨' },
  { prefix: '789-790', name: 'Brazil', code: 'BR', flag: '🇧🇷' },
  { prefix: '800-839', name: 'Italy', code: 'IT', flag: '🇮🇹' },
  { prefix: '840-849', name: 'Spain', code: 'ES', flag: '🇪🇸' },
  { prefix: '850', name: 'Cuba', code: 'CU', flag: '🇨🇺' },
  { prefix: '858', name: 'Slovakia', code: 'SK', flag: '🇸🇰' },
  { prefix: '859', name: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
  { prefix: '860', name: 'Serbia', code: 'RS', flag: '🇷🇸' },
  { prefix: '865', name: 'Mongolia', code: 'MN', flag: '🇲🇳' },
  { prefix: '867', name: 'North Korea', code: 'KP', flag: '🇰🇵' },
  { prefix: '868-869', name: 'Turkey', code: 'TR', flag: '🇹🇷' },
  { prefix: '870-879', name: 'Netherlands', code: 'NL', flag: '🇳🇱' },
  { prefix: '880', name: 'South Korea', code: 'KR', flag: '🇰🇷' },
  { prefix: '884', name: 'Cambodia', code: 'KH', flag: '🇰🇭' },
  { prefix: '885', name: 'Thailand', code: 'TH', flag: '🇹🇭' },
  { prefix: '888', name: 'Singapore', code: 'SG', flag: '🇸🇬' },
  { prefix: '890', name: 'India', code: 'IN', flag: '🇮🇳' },
  { prefix: '893', name: 'Vietnam', code: 'VN', flag: '🇻🇳' },
  { prefix: '896', name: 'Pakistan', code: 'PK', flag: '🇵🇰' },
  { prefix: '899', name: 'Indonesia', code: 'ID', flag: '🇮🇩' },
  { prefix: '900-919', name: 'Austria', code: 'AT', flag: '🇦🇹' },
  { prefix: '930-939', name: 'Australia', code: 'AU', flag: '🇦🇺' },
  { prefix: '940-949', name: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
  { prefix: '955', name: 'Malaysia', code: 'MY', flag: '🇲🇾' },
  { prefix: '958', name: 'Macau', code: 'MO', flag: '🇲🇴' },
];

export const getCountryFromBarcode = (barcode: string): CountryPrefix | undefined => {
  // EAN-13 is usually 13 digits. UPC-A is 12 digits (can be treated as 0 + UPC).
  let cleanCode = barcode.replace(/[^0-9]/g, '');
  
  if (cleanCode.length === 12) {
    cleanCode = '0' + cleanCode; // Convert UPC to EAN-13
  }
  
  if (cleanCode.length !== 13) return undefined;

  const prefixVal = parseInt(cleanCode.substring(0, 3));

  return gs1Prefixes.find(p => {
    if (p.prefix.includes('-')) {
      const [start, end] = p.prefix.split('-').map(Number);
      return prefixVal >= start && prefixVal <= end;
    }
    return prefixVal === Number(p.prefix);
  });
};